version: '3.7'

networks:
  rs-net:
    driver: bridge

services:
  test:
    image: ghcr.io/datakaveri/rs-test:latest
    env_file:
      - /home/ubuntu/configs/.rs.env
    volumes:
      - ./src/:/usr/share/app/src
      - /home/ubuntu/configs/rs-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir


    command: bash -c "docker/runTests.sh"
    networks: 
      - rs-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
  
  perfTest:
    image: ghcr.io/datakaveri/rs-test:latest
    env_file:
      - /home/ubuntu/configs/.rs.env
    volumes:
      - /home/ubuntu/configs/rs-config-dev.json:/usr/share/app/configs/config-dev.json
      - /home/ubuntu/configs/keystore-rs.jks:/usr/share/app/configs/keystore.jks
      - ./src:/usr/share/app/src
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir
    ports:
      - "8443:8443"
    restart: on-failure
    networks:
      - rs-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "mvn clean compile exec:java@resource-server"

volumes:
  rs-volume:
