version: '3.7'

networks:
  rs-net:
    driver: bridge

services:
  test:
    image: ghcr.io/datakaveri/rs-test:latest
    env_file:
      - /home/ubuntu/configs/5.5.0/.rs.env
    volumes:
      - ./src/:/usr/share/app/src
      - ./iudx-pmd-ruleset.xml:/usr/share/app/iudx-pmd-ruleset.xml
      - ./google_checks.xml:/usr/share/app/google_checks.xml
      - /home/ubuntu/configs/5.5.0/rs-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/5.5.0/keystore.jks:/usr/share/app/configs/keystore.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ${WORKSPACE}:/tmp/test
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir
    command: bash -c "docker/runTests.sh"
    network_mode: host
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
  
  perfTest:
    image: ghcr.io/datakaveri/rs-depl:latest
    env_file:
      - /home/ubuntu/configs/5.5.0/.rs.env
    volumes:
      - /home/ubuntu/configs/5.5.0/rs-config-dev.json:/usr/share/app/configs/config.json
      - /home/ubuntu/configs/5.5.0/keystore-rs.jks:/usr/share/app/configs/keystore.jks
      - type: volume
        source: rs-volume
        target: /usr/share/app/storage/temp-dir
    depends_on:
      - "zookeeper"
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - rs-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - rs-net

volumes:
  rs-volume:
