version: '3.7'

networks:
  rs-net:
    driver: bridge

services:

  prod:
    image: iudx/rs-depl:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - RS_JAVA_OPTS=-Xmx4096m
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - rs-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"


  dev:
    image: iudx/rs-dev:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - RS_JAVA_OPTS=-Xmx1024m
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - rs-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - rs-net
